services:
  voice-cloning-demo:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONFAULTHANDLER=1
      - COQUI_TOS_AGREED=1
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - hf_cache:/cache
volumes:
  hf_cache:
